language: node_js

node_js:
  - 'stable'
  - '8'
  - '6'

sudo: false

env:
  - workerCount=3

matrix:
  fast_finish: true

branches:
  only:
  - master
  - release-2.5
  - release-2.6

install:
  - npm uninstall typescript --no-save
  - npm uninstall tslint --no-save
  - npm install
  - if [ "$TRAVIS_NODE_VERSION" = "6" ]; then
      npm uninstall typemock --no-save;
      npm run build:typemock;
      npm install file:scripts/typemock --no-save;
    fi

cache:
  directories:
    - node_modules

git:
  depth: 1
